server:
  port: 8080
spring:
  application:
    name: eureka-client-a
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true # ????eureka???
    fetch-registry: true # ???????????
    registry-fetch-interval-seconds: 10 # ??????????
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true # ??ip
    lease-renewal-interval-in-seconds: 10 # ??????

#server:
#  port: 8080
#spring:
#  application:
#    name: eureka-client-a
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka, http://peer2:8762/eureka, http://peer3:8763/eureka
#    register-with-eureka: true # ????eureka???
#    fetch-registry: true # ???????????
#    registry-fetch-interval-seconds: 10 # ??????????
#  instance:
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    prefer-ip-address: true # ??ip
#    lease-renewal-interval-in-seconds: 10 # ??????