server:
  port: 8080
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://10.116.48.78:9411
  sleuth:
    sampler:
      probability: 0.1
      rate: 10
eureka:
  client:
    service-url:
      defaultZone: http://10.116.48.78:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}


