server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      enabled: true
      routes:
        - id: login-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/login
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://10.116.48.78:8761/eureka
    registry-fetch-interval-seconds: 3
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
